steps:
- name: 'ubuntu'
  args: ['bash', 'install-firefox.sh']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  env: ['NO_PROXY=0.0.0.0/9876', 'FIREFOX_BIN=/usr/bin/firefox']
  args: ['test', '--', '--singleRun', '--browsers=FirefoxHeadless']
